# Generated by Django 4.2.30 on 2026-09-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_authusuario_options_alter_usuario_options_and_more'),
        ('rutinas', '0002_remove_rutina_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='rutina',
            options={'verbose_name': 'Rutina', 'verbose_name_plural': 'Rutinas'},
        ),
        migrations.AlterModelOptions(
            name='rutinaejercicio',
            options={'ordering': ['orden'], 'verbose_name': 'Ejercicio de la rutina', 'verbose_name_plural': 'Ejercicios de la rutina'},
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('abdomen', 'Abdomen'), ('cuadriceps', 'Cuádriceps'), ('femoral', 'Femoral'), ('gluteos', 'Glúteos'), ('pantorrillas', 'Pantorrillas'), ('cardio', 'Cardio'), ('cuerpo_completo', 'Cuerpo Completo')], max_length=30, verbose_name='Grupo muscular'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la imagen'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del vídeo'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(blank=True, through='rutinas.RutinaEjercicio', to='rutinas.ejercicio', verbose_name='Ejercicios'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='es_favorita',
            field=models.BooleanField(default=False, verbose_name='Es favorita'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='users.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='descanso_segundos',
            field=models.IntegerField(default=60, verbose_name='Descanso (segundos)'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='repeticiones',
            field=models.IntegerField(default=10, verbose_name='Repeticiones'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina', verbose_name='Rutina'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='series',
            field=models.IntegerField(default=3, verbose_name='Series'),
        ),
    ]
