# Generated by Django 4.2.30 on 2026-09-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_alter_ejercicio_options_alter_rutina_options_and_more'),
    ]

    operations = [
    ]
