# Generated by Django 4.2.30 on 2026-09-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_completar_catalogo_ejercicios'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ejercicio',
            table='rutinas_ejercicios',
        ),
        migrations.AlterModelTable(
            name='rutina',
            table='rutinas_rutinas',
        ),
    ]
