# Generated by Django 4.2.30 on 2026-07-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_sesion_recuperacionpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionIa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('rutina', 'Generación de rutina'), ('nutricion', 'Consulta de nutrición'), ('general', 'Consulta general')], max_length=13, null=True)),
                ('mensaje_usuario', models.TextField()),
                ('respuesta_ia', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_ia', to='users.usuario')),
            ],
            options={
                'db_table': 'conversaciones_ia',
                'ordering': ['-created_at'],
            },
        ),
    ]
