# Generated by Django 4.2.30 on 2026-07-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0002_agregar_columnas_nuevas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='dia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nivel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='rango_imc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]