# Generated by Django 4.2.30 on 2026-07-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0003_alter_ejercicio_dia_alter_ejercicio_grupo_muscular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historialentrenamiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProgresoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_realizadas', models.IntegerField(blank=True, null=True)),
                ('repeticiones_realizadas', models.IntegerField(blank=True, null=True)),
                ('peso_usado', models.FloatField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(db_column='ejercicio_id', on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.ejercicio')),
                ('historial', models.ForeignKey(db_column='historial_id', on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='entrenamientos.historialentrenamiento')),
            ],
            options={
                'db_table': 'progreso_ejercicios',
            },
        ),
    ]
