# Generated by Django 4.2.30 on 2026-07-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_sesion_recuperacionpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pecho', models.FloatField(blank=True, null=True)),
                ('cintura', models.FloatField(blank=True, null=True)),
                ('cadera', models.FloatField(blank=True, null=True)),
                ('brazo_izquierdo', models.FloatField(blank=True, null=True)),
                ('brazo_derecho', models.FloatField(blank=True, null=True)),
                ('pierna_izquierda', models.FloatField(blank=True, null=True)),
                ('pierna_derecha', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='medidas_corporales', to='users.usuario')),
            ],
            options={
                'db_table': 'medidas_corporales',
            },
        ),
        migrations.CreateModel(
            name='ImcHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='imc_historial', to='users.usuario')),
            ],
            options={
                'db_table': 'imc_historial',
            },
        ),
    ]
