# Generated by Django 4.2.30 on 2026-07-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_sesion_recuperacionpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=8, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calorias', models.FloatField(blank=True, null=True)),
                ('proteinas_g', models.FloatField(blank=True, null=True)),
                ('carbohidratos_g', models.FloatField(blank=True, null=True)),
                ('grasas_g', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comidas',
            },
        ),
        migrations.CreateModel(
            name='RegistroComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comida', models.ForeignKey(db_column='comida_id', on_delete=django.db.models.deletion.CASCADE, to='nutricion.comida')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_comida', to='users.usuario')),
            ],
            options={
                'db_table': 'registro_comidas',
            },
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calorias_diarias', models.FloatField(blank=True, null=True)),
                ('proteinas_g', models.FloatField(blank=True, null=True)),
                ('carbohidratos_g', models.FloatField(blank=True, null=True)),
                ('grasas_g', models.FloatField(blank=True, null=True)),
                ('generada_por_ia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to='users.usuario')),
            ],
            options={
                'db_table': 'planes_nutricionales',
            },
        ),
        migrations.AddField(
            model_name='comida',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='nutricion.plannutricional'),
        ),
    ]
