# Generated by Django 4.2.30 on 2026-09-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0004_cargar_catalogo_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comida',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Comida del plan', 'verbose_name_plural': 'Comidas del plan'},
        ),
        migrations.AlterModelOptions(
            name='plannutricional',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plan alimenticio', 'verbose_name_plural': 'Planes alimenticios'},
        ),
        migrations.AlterModelOptions(
            name='registrocomida',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Comida registrada', 'verbose_name_plural': 'Comidas registradas'},
        ),
    ]
