# Generated by Django 4.2.30 on 2026-10-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_authusuario_options_alter_ejercicio_options_and_more'),
        ('nutricion', '0007_categoriaalimento_alimento_comida_alimento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plannutricional',
            unique_together={('usuario', 'nombre')},
        ),
    ]
