# Generated by Django 4.2 on 2026-08-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authusuario_last_login_authusuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wger_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=100)),
                ('musculos_principales', models.JSONField(blank=True, default=list)),
                ('musculos_secundarios', models.JSONField(blank=True, default=list)),
                ('equipamiento', models.JSONField(blank=True, default=list)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True, max_length=500)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biblioteca_ejercicios',
                'ordering': ['nombre'],
            },
        ),
    ]
