# Generated by Django 4.2.30 on 2026-09-19 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authusuario_groups_authusuario_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authusuario',
            options={'verbose_name': 'Cuenta de acceso', 'verbose_name_plural': 'Cuentas de acceso'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuario'},
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de verificación'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='intentos_fallidos',
            field=models.IntegerField(default=0, verbose_name='Intentos fallidos'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acceso al administrador'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hash de contraseña'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='token_expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento del token'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último inicio de sesión'),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Cuenta verificada'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de acceso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meta',
            field=models.CharField(blank=True, choices=[('perder_peso', 'Perder Peso'), ('ganar_musculo', 'Ganar Músculo'), ('mantenerse', 'Mantenerse'), ('mejorar_resistencia', 'Mejorar Resistencia')], max_length=30, null=True, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
    ]
