# Generated by Django 4.2 on 2026-08-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ejercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='equipamiento',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='wger_id',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_final',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_inicio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='repdb_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
