# Generated by Django 4.2 on 2026-08-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sesion_recuperacionpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_fin_plan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_inicio_plan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
