# Generated by Django 4.2 on 2026-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_authusuario_options_alter_usuario_options_and_more'),
        ('users', '0004_remove_ejercicio_equipamiento_and_more'),
        ('users', '0005_alter_authusuario_id_alter_recuperacionpassword_id_and_more'),
    ]

    operations = [
    ]
