# Generated by Django 4.2 on 2026-10-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20261006_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authusuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_fin_plan',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_inicio_plan',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='plan',
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='password_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meta',
            field=models.CharField(blank=True, choices=[('perder_peso', 'Perder Peso'), ('ganar_musculo', 'Ganar Músculo'), ('mantenerse', 'Mantenerse'), ('mejorar_resistencia', 'Mejorar Resistencia')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
