# Generated by Django 4.2.30 on 2026-09-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_authusuario_options_alter_usuario_options_and_more'),
        ('users', '0004_remove_ejercicio_equipamiento_and_more'),
        ('users', '0006_pago'),
    ]

    operations = [
    ]
