# Generated by Django 4.2.30 on 2026-10-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_authusuario_options_alter_usuario_options_and_more'),
        ('users', '0007_merge_20260929_1516'),
    ]

    operations = [
    ]
