import os
import django

if __name__ == '__main__':
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'body_rhythm_api.settings')
    django.setup()

from entrenamientos.models import Ejercicio, Rutina


def ejecutar_seed():
    print("Iniciando seed de entrenamientos...")

    rutinas_data = [
        # PERDER PESO
        {
            "nombre": "Quema Activa - Bajo Peso",
            "descripcion": "Cardio suave y tonificacion para bajo peso.",
            "nivel": "principiante",
            "objetivo": "perder_peso",
            "rango_imc": "bajo_peso",
            "imc_referencia": 17.0,
            "dias_por_semana": 3,
            "duracion_minutos": 35,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida", "descripcion": "Caminar a paso rapido 20 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1200, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso", "descripcion": "Sentadilla con peso corporal.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha", "descripcion": "Mantener posicion de plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 30, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Crunches", "descripcion": "Abdominales clasicos.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica", "descripcion": "Pedaleo continuo moderado.", "series": 1, "repeticiones": None, "duracion_segundos": 1200, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Zancadas", "descripcion": "Pasos largos alternando piernas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Puente de gluteos", "descripcion": "Elevar cadera apretando gluteos.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Elevaciones laterales", "descripcion": "Elevar brazos al lado hasta hombro.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "hombros", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Trote suave", "descripcion": "Correr a ritmo lento y constante.", "series": 1, "repeticiones": None, "duracion_segundos": 900, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Flexiones de rodillas", "descripcion": "Flexiones apoyando rodillas.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "pecho", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Superman", "descripcion": "Levantar brazos y piernas boca abajo.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Bicicleta abdominal", "descripcion": "Codo con rodilla opuesta alternado.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "viernes"},
            ]
        },
        {
            "nombre": "Cardio Moderado - Normal",
            "descripcion": "Cardio y fuerza para IMC normal que quiere reducir grasa.",
            "nivel": "intermedio",
            "objetivo": "perder_peso",
            "rango_imc": "normal",
            "imc_referencia": 22.0,
            "dias_por_semana": 4,
            "duracion_minutos": 45,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Saltos de tijera", "descripcion": "Jumping jacks continuos.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 30, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso lunes", "descripcion": "Sentadilla con peso corporal.", "series": 4, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Flexiones estandar", "descripcion": "Flexiones de brazos completas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Plancha lunes", "descripcion": "Posicion de plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 40, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Trote suave martes", "descripcion": "Correr 30 min a ritmo bajo.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Zancadas martes", "descripcion": "Pasos largos alternos.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Puente de gluteos martes", "descripcion": "Elevar cadera.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Crunches martes", "descripcion": "Abdominales clasicos.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Mountain climbers", "descripcion": "Rodillas al pecho en plancha rapido.", "series": 3, "repeticiones": None, "duracion_segundos": 45, "descanso_segundos": 45, "orden": 1, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Sentadilla sin peso jueves", "descripcion": "Sentadilla corporal.", "series": 4, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Remo con mancuerna", "descripcion": "Tirar mancuerna hacia la cadera.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "espalda", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Elevacion de piernas", "descripcion": "Levantar piernas rectas a 90 grados.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Cuerda de saltar", "descripcion": "Saltar cuerda ritmo constante.", "series": 3, "repeticiones": None, "duracion_segundos": 120, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "intermedio", "dia": "sabado"},
                {"nombre": "Step up", "descripcion": "Subir y bajar de escalon alternando.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Flexiones estandar sabado", "descripcion": "Flexiones completas.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "sabado"},
                {"nombre": "Bicicleta abdominal sabado", "descripcion": "Alternando codo-rodilla.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "sabado"},
            ]
        },
        {
            "nombre": "Cardio Intenso - Sobrepeso",
            "descripcion": "Cardio bajo impacto y fuerza para sobrepeso.",
            "nivel": "principiante",
            "objetivo": "perder_peso",
            "rango_imc": "sobrepeso",
            "imc_referencia": 27.0,
            "dias_por_semana": 4,
            "duracion_minutos": 50,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida lunes", "descripcion": "Caminata 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso sp l", "descripcion": "Sentadilla corporal.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Puente gluteos sp l", "descripcion": "Elevar cadera.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha sp l", "descripcion": "Posicion de plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 30, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica sp m", "descripcion": "Pedaleo 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Step up sp m", "descripcion": "Subir y bajar escalon.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Flexiones rodillas sp m", "descripcion": "Flexiones con rodillas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Crunches sp m", "descripcion": "Abdominales clasicos.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Caminata rapida sp j", "descripcion": "Caminata 25 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1500, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Zancadas sp j", "descripcion": "Pasos largos alternos.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Superman sp j", "descripcion": "Levantar brazos y piernas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Elevacion piernas sp j", "descripcion": "Piernas rectas a 90 grados.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Bicicleta estatica sp s", "descripcion": "Pedaleo 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Sentadilla sumo sp s", "descripcion": "Sentadilla pies anchos.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Elevaciones laterales sp s", "descripcion": "Elevar brazos al lado.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "hombros", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Bicicleta abdominal sp s", "descripcion": "Codo-rodilla alternado.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "sabado"},
            ]
        },
        {
            "nombre": "Movimiento Suave - Obesidad",
            "descripcion": "Bajo impacto, movilidad y cardio suave para obesidad.",
            "nivel": "principiante",
            "objetivo": "perder_peso",
            "rango_imc": "obesidad",
            "imc_referencia": 33.0,
            "dias_por_semana": 3,
            "duracion_minutos": 40,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida ob l", "descripcion": "Caminata 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso ob l", "descripcion": "Sentadilla suave.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Puente gluteos ob l", "descripcion": "Elevar cadera despacio.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha ob l", "descripcion": "Plancha corta.", "series": 3, "repeticiones": None, "duracion_segundos": 20, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica ob m", "descripcion": "Pedaleo suave 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Step up ob m", "descripcion": "Subir y bajar escalon lento.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Superman ob m", "descripcion": "Levantar extremidades boca abajo.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Crunches ob m", "descripcion": "Abdominales suaves.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Caminata rapida ob v", "descripcion": "Caminata 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Sentadilla sumo ob v", "descripcion": "Sentadilla pies anchos suave.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Elevacion pantorrillas ob v", "descripcion": "Elevar talones de pie.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "pantorrillas", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Elevacion piernas ob v", "descripcion": "Piernas rectas a 90 grados.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "viernes"},
            ]
        },

        # GANAR MUSCULO
        {
            "nombre": "Volumen Base - Bajo Peso",
            "descripcion": "Fuerza progresiva para ganar masa muscular en bajo peso.",
            "nivel": "intermedio",
            "objetivo": "ganar_musculo",
            "rango_imc": "bajo_peso",
            "imc_referencia": 17.0,
            "dias_por_semana": 4,
            "duracion_minutos": 55,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Press pecho mancuernas gm l", "descripcion": "Press de pecho con mancuernas.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Flexiones estandar gm l", "descripcion": "Flexiones completas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Flexiones diamante gm l", "descripcion": "Flexiones manos en diamante.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 3, "grupo_muscular": "pecho", "nivel": "avanzado", "dia": "lunes"},
                {"nombre": "Plancha gm l", "descripcion": "Plancha sostenida.", "series": 3, "repeticiones": None, "duracion_segundos": 45, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla mancuernas gm ma", "descripcion": "Sentadilla con mancuernas.", "series": 4, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cuadriceps", "nivel": "intermedio", "dia": "martes"},
                {"nombre": "Peso muerto mancuernas gm ma", "descripcion": "Peso muerto con mancuernas.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "isquiotibiales", "nivel": "intermedio", "dia": "martes"},
                {"nombre": "Zancadas gm ma", "descripcion": "Zancadas alternando piernas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Elevacion pantorrillas gm ma", "descripcion": "Elevar talones.", "series": 4, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "pantorrillas", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Jalon al pecho gm j", "descripcion": "Jalar barra hacia pecho.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "espalda", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Remo mancuerna gm j", "descripcion": "Remo unilateral.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "espalda", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Superman gm j", "descripcion": "Levantar extremidades boca abajo.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Bicicleta abdominal gm j", "descripcion": "Codo-rodilla alternado.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Press hombros gm v", "descripcion": "Press sobre la cabeza.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "hombros", "nivel": "intermedio", "dia": "viernes"},
                {"nombre": "Elevaciones laterales gm v", "descripcion": "Elevar brazos lateral.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "hombros", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Sentadilla sumo gm v", "descripcion": "Sentadilla pies anchos.", "series": 4, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 90, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Puente gluteos gm v", "descripcion": "Elevar cadera.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "viernes"},
            ]
        },
        {
            "nombre": "Hipertrofia Equilibrada - Normal",
            "descripcion": "Hipertrofia para IMC normal con ejercicios compuestos.",
            "nivel": "intermedio",
            "objetivo": "ganar_musculo",
            "rango_imc": "normal",
            "imc_referencia": 22.0,
            "dias_por_semana": 4,
            "duracion_minutos": 60,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Press pecho mn l", "descripcion": "Press con mancuernas.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Flexiones diamante mn l", "descripcion": "Flexiones en diamante.", "series": 4, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "pecho", "nivel": "avanzado", "dia": "lunes"},
                {"nombre": "Elevaciones laterales mn l", "descripcion": "Lateral raises.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "hombros", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Press hombros mn l", "descripcion": "Press overhead.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 4, "grupo_muscular": "hombros", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Sentadilla mancuernas mn ma", "descripcion": "Squat con mancuernas.", "series": 5, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cuadriceps", "nivel": "intermedio", "dia": "martes"},
                {"nombre": "Peso muerto mn ma", "descripcion": "Deadlift con mancuernas.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "isquiotibiales", "nivel": "intermedio", "dia": "martes"},
                {"nombre": "Sentadilla sumo mn ma", "descripcion": "Sumo squat.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 90, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Elevacion pantorrillas mn ma", "descripcion": "Calf raises.", "series": 4, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "pantorrillas", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Jalon pecho mn j", "descripcion": "Lat pulldown.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "espalda", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Remo mancuerna mn j", "descripcion": "Row unilateral.", "series": 4, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "espalda", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Dominadas asistidas mn j", "descripcion": "Pull-up con banda.", "series": 3, "repeticiones": 8, "duracion_segundos": None, "descanso_segundos": 120, "orden": 3, "grupo_muscular": "espalda", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Elevacion piernas mn j", "descripcion": "Leg raises.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Burpees mn s", "descripcion": "Burpees completos.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cuerpo_completo", "nivel": "intermedio", "dia": "sabado"},
                {"nombre": "Zancadas mn s", "descripcion": "Lunges alternos.", "series": 4, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Puente gluteos mn s", "descripcion": "Hip thrust.", "series": 4, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Bicicleta abdominal mn s", "descripcion": "Bicycle crunches.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "sabado"},
            ]
        },
        {
            "nombre": "Fuerza y Definicion - Sobrepeso",
            "descripcion": "Fuerza con cardio moderado para sobrepeso.",
            "nivel": "principiante",
            "objetivo": "ganar_musculo",
            "rango_imc": "sobrepeso",
            "imc_referencia": 27.0,
            "dias_por_semana": 3,
            "duracion_minutos": 55,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida gms l", "descripcion": "Cardio 10 min.", "series": 1, "repeticiones": None, "duracion_segundos": 600, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso gms l", "descripcion": "Squat corporal.", "series": 4, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Flexiones rodillas gms l", "descripcion": "Flexiones con rodillas.", "series": 4, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha gms l", "descripcion": "Plancha sostenida.", "series": 3, "repeticiones": None, "duracion_segundos": 40, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica gms m", "descripcion": "Cardio 10 min.", "series": 1, "repeticiones": None, "duracion_segundos": 600, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Puente gluteos gms m", "descripcion": "Hip thrust.", "series": 4, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Superman gms m", "descripcion": "Back extension.", "series": 4, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Crunches gms m", "descripcion": "Abdominales.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Trote suave gms v", "descripcion": "Cardio 10 min.", "series": 1, "repeticiones": None, "duracion_segundos": 600, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Zancadas gms v", "descripcion": "Lunges.", "series": 4, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Press pecho gms v", "descripcion": "Press con mancuernas.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 3, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "viernes"},
                {"nombre": "Elevaciones laterales gms v", "descripcion": "Lateral raises.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "hombros", "nivel": "principiante", "dia": "viernes"},
            ]
        },
        {
            "nombre": "Activacion Progresiva - Obesidad",
            "descripcion": "Fuerza bajo impacto para obesidad.",
            "nivel": "principiante",
            "objetivo": "ganar_musculo",
            "rango_imc": "obesidad",
            "imc_referencia": 33.0,
            "dias_por_semana": 3,
            "duracion_minutos": 40,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida gmo l", "descripcion": "Cardio 15 min.", "series": 1, "repeticiones": None, "duracion_segundos": 900, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso gmo l", "descripcion": "Squat suave.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Puente gluteos gmo l", "descripcion": "Hip thrust.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha gmo l", "descripcion": "Plancha corta.", "series": 3, "repeticiones": None, "duracion_segundos": 20, "descanso_segundos": 90, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica gmo m", "descripcion": "Cardio 15 min.", "series": 1, "repeticiones": None, "duracion_segundos": 900, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Flexiones rodillas gmo m", "descripcion": "Flexiones con rodillas.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "pecho", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Superman gmo m", "descripcion": "Back extension.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Crunches gmo m", "descripcion": "Abdominales suaves.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Caminata rapida gmo v", "descripcion": "Cardio 15 min.", "series": 1, "repeticiones": None, "duracion_segundos": 900, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Step up gmo v", "descripcion": "Subir escalon.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Elevaciones laterales gmo v", "descripcion": "Lateral raises.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "hombros", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Sentadilla sumo gmo v", "descripcion": "Sumo squat.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 4, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "viernes"},
            ]
        },

        # MANTENERSE
        {
            "nombre": "Balance Corporal - Bajo Peso",
            "descripcion": "Fuerza y cardio equilibrado para mantener peso en bajo peso.",
            "nivel": "intermedio",
            "objetivo": "mantenerse",
            "rango_imc": "bajo_peso",
            "imc_referencia": 17.0,
            "dias_por_semana": 3,
            "duracion_minutos": 45,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Trote suave mb l", "descripcion": "Trote 20 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1200, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla mancuernas mb l", "descripcion": "Squat con peso.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Flexiones estandar mb l", "descripcion": "Push-up completas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Plancha mb l", "descripcion": "Plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 40, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica mb m", "descripcion": "Cardio 20 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1200, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Jalon pecho mb m", "descripcion": "Lat pulldown.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "espalda", "nivel": "intermedio", "dia": "miercoles"},
                {"nombre": "Press hombros mb m", "descripcion": "Press overhead.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "hombros", "nivel": "intermedio", "dia": "miercoles"},
                {"nombre": "Bicicleta abdominal mb m", "descripcion": "Bicycle crunches.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "miercoles"},
                {"nombre": "Saltos tijera mb v", "descripcion": "Jumping jacks.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 30, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Peso muerto mb v", "descripcion": "Deadlift mancuernas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "isquiotibiales", "nivel": "intermedio", "dia": "viernes"},
                {"nombre": "Zancadas mb v", "descripcion": "Lunges.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Elevacion piernas mb v", "descripcion": "Leg raises.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "viernes"},
            ]
        },
        {
            "nombre": "Mantenimiento Total - Normal",
            "descripcion": "Programa completo para mantener peso con IMC normal.",
            "nivel": "intermedio",
            "objetivo": "mantenerse",
            "rango_imc": "normal",
            "imc_referencia": 22.0,
            "dias_por_semana": 3,
            "duracion_minutos": 45,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Trote suave mn2 l", "descripcion": "Trote 25 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1500, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso mn2 l", "descripcion": "Bodyweight squat.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Flexiones estandar mn2 l", "descripcion": "Push-up.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Plancha mn2 l", "descripcion": "Plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 40, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Cuerda saltar mn2 m", "descripcion": "Saltar cuerda.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 45, "orden": 1, "grupo_muscular": "cardio", "nivel": "intermedio", "dia": "miercoles"},
                {"nombre": "Remo mancuerna mn2 m", "descripcion": "Row.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "espalda", "nivel": "intermedio", "dia": "miercoles"},
                {"nombre": "Puente gluteos mn2 m", "descripcion": "Hip thrust.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Crunches mn2 m", "descripcion": "Abdominales.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Bicicleta estatica mn2 v", "descripcion": "Cardio 25 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1500, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Zancadas mn2 v", "descripcion": "Lunges.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Elevaciones laterales mn2 v", "descripcion": "Lateral raises.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "hombros", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Bicicleta abdominal mn2 v", "descripcion": "Bicycle crunches.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "viernes"},
            ]
        },
        {
            "nombre": "Control de Peso - Sobrepeso",
            "descripcion": "Cardio y tono para mantener peso con sobrepeso.",
            "nivel": "principiante",
            "objetivo": "mantenerse",
            "rango_imc": "sobrepeso",
            "imc_referencia": 27.0,
            "dias_por_semana": 3,
            "duracion_minutos": 45,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida ms l", "descripcion": "Caminata 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso ms l", "descripcion": "Squat.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Flexiones rodillas ms l", "descripcion": "Push-up rodillas.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha ms l", "descripcion": "Plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 30, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica ms m", "descripcion": "Cardio 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Step up ms m", "descripcion": "Step.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Superman ms m", "descripcion": "Back extension.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Crunches ms m", "descripcion": "Abdominales.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Caminata rapida ms v", "descripcion": "Caminata 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Puente gluteos ms v", "descripcion": "Hip thrust.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Elevaciones laterales ms v", "descripcion": "Lateral raises.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "hombros", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Elevacion piernas ms v", "descripcion": "Leg raises.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "viernes"},
            ]
        },
        {
            "nombre": "Estabilidad Activa - Obesidad",
            "descripcion": "Rutina suave para mantener condicion fisica en obesidad.",
            "nivel": "principiante",
            "objetivo": "mantenerse",
            "rango_imc": "obesidad",
            "imc_referencia": 33.0,
            "dias_por_semana": 3,
            "duracion_minutos": 35,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida mo l", "descripcion": "Caminata 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Sentadilla sin peso mo l", "descripcion": "Squat suave.", "series": 3, "repeticiones": 8, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha mo l", "descripcion": "Plancha corta.", "series": 3, "repeticiones": None, "duracion_segundos": 20, "descanso_segundos": 90, "orden": 3, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica mo m", "descripcion": "Cardio 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Puente gluteos mo m", "descripcion": "Hip thrust.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Crunches mo m", "descripcion": "Abdominales.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Caminata rapida mo v", "descripcion": "Caminata 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Superman mo v", "descripcion": "Back extension.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "viernes"},
                {"nombre": "Elevacion pantorrillas mo v", "descripcion": "Calf raises.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "pantorrillas", "nivel": "principiante", "dia": "viernes"},
            ]
        },

        # MEJORAR RESISTENCIA
        {
            "nombre": "Resistencia Base - Bajo Peso",
            "descripcion": "Cardio progresivo para mejorar resistencia en bajo peso.",
            "nivel": "intermedio",
            "objetivo": "mejorar_resistencia",
            "rango_imc": "bajo_peso",
            "imc_referencia": 17.0,
            "dias_por_semana": 4,
            "duracion_minutos": 50,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Trote suave rb l", "descripcion": "Trote 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Saltos tijera rb l", "descripcion": "Jumping jacks.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 30, "orden": 2, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Mountain climbers rb l", "descripcion": "Rodillas al pecho rapido.", "series": 3, "repeticiones": None, "duracion_segundos": 45, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Plancha rb l", "descripcion": "Plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 45, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica rb ma", "descripcion": "Cardio 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Sentadilla sin peso rb ma", "descripcion": "Squat.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Flexiones estandar rb ma", "descripcion": "Push-up.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "martes"},
                {"nombre": "Crunches rb ma", "descripcion": "Abdominales.", "series": 3, "repeticiones": 25, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Carrera intervalada rb j", "descripcion": "Sprints alternados.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "avanzado", "dia": "jueves"},
                {"nombre": "Burpees rb j", "descripcion": "Burpees completos.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuerpo_completo", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Zancadas rb j", "descripcion": "Lunges.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Bicicleta abdominal rb j", "descripcion": "Bicycle crunches.", "series": 3, "repeticiones": 25, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Cuerda saltar rb s", "descripcion": "Saltar cuerda.", "series": 4, "repeticiones": None, "duracion_segundos": 120, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "intermedio", "dia": "sabado"},
                {"nombre": "Mountain climbers rb s", "descripcion": "Rodillas al pecho.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "sabado"},
                {"nombre": "Sentadilla sin peso rb s", "descripcion": "Squat.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Plancha rb s", "descripcion": "Plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "sabado"},
            ]
        },
        {
            "nombre": "Cardio Avanzado - Normal",
            "descripcion": "Alta intensidad para resistencia cardiovascular en IMC normal.",
            "nivel": "avanzado",
            "objetivo": "mejorar_resistencia",
            "rango_imc": "normal",
            "imc_referencia": 22.0,
            "dias_por_semana": 5,
            "duracion_minutos": 55,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Carrera intervalada rn l", "descripcion": "Sprints 30 min.", "series": 1, "repeticiones": None, "duracion_segundos": 1800, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "avanzado", "dia": "lunes"},
                {"nombre": "Burpees rn l", "descripcion": "Burpees.", "series": 4, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuerpo_completo", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Mountain climbers rn l", "descripcion": "Rodillas rapido.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "lunes"},
                {"nombre": "Plancha rn l", "descripcion": "Plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Cuerda saltar rn ma", "descripcion": "Jump rope.", "series": 4, "repeticiones": None, "duracion_segundos": 120, "descanso_segundos": 45, "orden": 1, "grupo_muscular": "cardio", "nivel": "intermedio", "dia": "martes"},
                {"nombre": "Sentadilla sin peso rn ma", "descripcion": "Squat.", "series": 4, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Flexiones estandar rn ma", "descripcion": "Push-up.", "series": 4, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "intermedio", "dia": "martes"},
                {"nombre": "Elevacion piernas rn ma", "descripcion": "Leg raises.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "martes"},
                {"nombre": "Trote suave rn mi", "descripcion": "Trote 50 min.", "series": 1, "repeticiones": None, "duracion_segundos": 3000, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Zancadas rn mi", "descripcion": "Lunges.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Superman rn mi", "descripcion": "Back extension.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Bicicleta abdominal rn mi", "descripcion": "Bicycle.", "series": 3, "repeticiones": 25, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "miercoles"},
                {"nombre": "Burpees rn j", "descripcion": "Burpees.", "series": 4, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cuerpo_completo", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Mountain climbers rn j", "descripcion": "Rodillas rapido.", "series": 4, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 45, "orden": 2, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Sentadilla sin peso rn j", "descripcion": "Squat.", "series": 4, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Plancha rn j", "descripcion": "Plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 60, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Carrera intervalada rn s", "descripcion": "Sprints 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "avanzado", "dia": "sabado"},
                {"nombre": "Cuerda saltar rn s", "descripcion": "Jump rope.", "series": 3, "repeticiones": None, "duracion_segundos": 120, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cardio", "nivel": "intermedio", "dia": "sabado"},
                {"nombre": "Step up rn s", "descripcion": "Step.", "series": 3, "repeticiones": 20, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Crunches rn s", "descripcion": "Abdominales.", "series": 3, "repeticiones": 25, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "sabado"},
            ]
        },
        {
            "nombre": "Cardio Adaptado - Sobrepeso",
            "descripcion": "Cardio bajo impacto para resistencia en sobrepeso.",
            "nivel": "principiante",
            "objetivo": "mejorar_resistencia",
            "rango_imc": "sobrepeso",
            "imc_referencia": 27.0,
            "dias_por_semana": 4,
            "duracion_minutos": 50,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida rs l", "descripcion": "Caminata 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Step up rs l", "descripcion": "Step.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Puente gluteos rs l", "descripcion": "Hip thrust.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha rs l", "descripcion": "Plancha.", "series": 3, "repeticiones": None, "duracion_segundos": 30, "descanso_segundos": 60, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica rs m", "descripcion": "Cardio 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Sentadilla sin peso rs m", "descripcion": "Squat.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Flexiones rodillas rs m", "descripcion": "Push-up rodillas.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "pecho", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Crunches rs m", "descripcion": "Abdominales.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "miercoles"},
                {"nombre": "Caminata rapida rs j", "descripcion": "Caminata 40 min.", "series": 1, "repeticiones": None, "duracion_segundos": 2400, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Zancadas rs j", "descripcion": "Lunges.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Superman rs j", "descripcion": "Back extension.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Bicicleta abdominal rs j", "descripcion": "Bicycle.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "jueves"},
                {"nombre": "Bicicleta estatica rs s", "descripcion": "Cardio 50 min.", "series": 1, "repeticiones": None, "duracion_segundos": 3000, "descanso_segundos": 60, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Step up rs s", "descripcion": "Step.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Sentadilla sumo rs s", "descripcion": "Sumo squat.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Elevacion piernas rs s", "descripcion": "Leg raises.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 45, "orden": 4, "grupo_muscular": "abdomen", "nivel": "intermedio", "dia": "sabado"},
            ]
        },
        {
            "nombre": "Resistencia Suave - Obesidad",
            "descripcion": "Cardio muy bajo impacto para resistencia en obesidad.",
            "nivel": "principiante",
            "objetivo": "mejorar_resistencia",
            "rango_imc": "obesidad",
            "imc_referencia": 33.0,
            "dias_por_semana": 4,
            "duracion_minutos": 40,
            "generada_por_ia": False,
            "ejercicios": [
                {"nombre": "Caminata rapida ro l", "descripcion": "Caminata 50 min.", "series": 1, "repeticiones": None, "duracion_segundos": 3000, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Step up ro l", "descripcion": "Step.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Plancha ro l", "descripcion": "Plancha corta.", "series": 3, "repeticiones": None, "duracion_segundos": 20, "descanso_segundos": 90, "orden": 3, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "lunes"},
                {"nombre": "Bicicleta estatica ro ma", "descripcion": "Cardio 50 min.", "series": 1, "repeticiones": None, "duracion_segundos": 3000, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Sentadilla sin peso ro ma", "descripcion": "Squat suave.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Crunches ro ma", "descripcion": "Abdominales.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "abdomen", "nivel": "principiante", "dia": "martes"},
                {"nombre": "Caminata rapida ro j", "descripcion": "Caminata 50 min.", "series": 1, "repeticiones": None, "duracion_segundos": 3000, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Puente gluteos ro j", "descripcion": "Hip thrust.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 60, "orden": 2, "grupo_muscular": "gluteos", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Superman ro j", "descripcion": "Back extension.", "series": 3, "repeticiones": 10, "duracion_segundos": None, "descanso_segundos": 60, "orden": 3, "grupo_muscular": "espalda", "nivel": "principiante", "dia": "jueves"},
                {"nombre": "Bicicleta estatica ro s", "descripcion": "Cardio 60 min.", "series": 1, "repeticiones": None, "duracion_segundos": 3600, "descanso_segundos": 90, "orden": 1, "grupo_muscular": "cardio", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Step up ro s", "descripcion": "Step.", "series": 3, "repeticiones": 12, "duracion_segundos": None, "descanso_segundos": 90, "orden": 2, "grupo_muscular": "cuadriceps", "nivel": "principiante", "dia": "sabado"},
                {"nombre": "Elevacion pantorrillas ro s", "descripcion": "Calf raises.", "series": 3, "repeticiones": 15, "duracion_segundos": None, "descanso_segundos": 45, "orden": 3, "grupo_muscular": "pantorrillas", "nivel": "principiante", "dia": "sabado"},
            ]
        },
    ]

    rutinas_creadas = 0
    ejercicios_creados = 0

    for rd in rutinas_data:
        rutina, created = Rutina.objects.get_or_create(
            objetivo=rd['objetivo'],
            rango_imc=rd['rango_imc'],
            defaults={
                'nombre': rd['nombre'],
                'descripcion': rd['descripcion'],
                'nivel': rd['nivel'],
                'imc_referencia': rd['imc_referencia'],
                'dias_por_semana': rd['dias_por_semana'],
                'duracion_minutos': rd['duracion_minutos'],
                'generada_por_ia': rd['generada_por_ia'],
                'usuario': None,
            }
        )

        if created:
            rutinas_creadas += 1
            print(f"Rutina creada: {rd['nombre']}")

            for ej in rd['ejercicios']:
                Ejercicio.objects.create(
                    rutina=rutina,
                    nombre=ej['nombre'],
                    descripcion=ej['descripcion'],
                    series=ej['series'],
                    repeticiones=ej['repeticiones'],
                    duracion_segundos=ej['duracion_segundos'],
                    descanso_segundos=ej['descanso_segundos'],
                    orden=ej['orden'],
                    grupo_muscular=ej['grupo_muscular'],
                    nivel=ej['nivel'],
                    dia=ej['dia'],
                )
                ejercicios_creados += 1
        else:
            print(f"Rutina ya existe: {rd['nombre']}")

    print(f"\nSeed completado: {rutinas_creadas} rutinas, {ejercicios_creados} ejercicios creados.")


ejecutar_seed()